version: '2'

services:
  postgres:
    image: mdillon/postgis:10
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    tmpfs:
      - /run
      - /tmp

  initdb:
    image: hammermc/renderd-docker
    restart: "no"
    depends_on:
      - postgres
    env_file:
      - osm.env
    environment:
      - REDOWNLOAD
      - REINITDB
      - http_proxy
      - https_proxy
    command: renderd-initdb
    volumes:
      - maps-data:/data
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /run
      - /tmp

  renderd:
    image: hammermc/renderd-docker
    restart: always
    env_file:
      - osm.env
    depends_on:
      - postgres
      - initdb
    # you can run renderd with custom options with (eg)
    # command: renderd renderd -f --config=/etc/renderd.conf
    # the two "renderd renderd" is required, the first selects the block to run in docker-entrypoint.sh
    # the second is the executable to run, ie it could be renderd cat /etc/renderd.conf to copy the renderd.conf
    command: renderd
    volumes:
      - maps-data:/data
      - ./renderd/renderd.conf:/etc/renderd.conf
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /run
      - /tmp

  apache:
    image: hammermc/renderd-docker
    restart: always
    depends_on:
      - renderd
    # you can run apache2 with custom options with (eg)
    # command: renderd-apache2 apache2 -DFOREGROUND -f /etc/apache2/apache2.conf
    command: renderd-apache2
    volumes:
      - maps-data:/data
      - ./renderd/renderd.conf:/etc/renderd.conf
      - ./apache/tileserver_site.conf:/etc/apache2/sites-available/tileserver_site.conf
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /run
      - /tmp
    ports:
      - 80:80

volumes:
  maps-data:
  postgres-data:
