version: '2'

services:
  postgres:
    image: mdillon/postgis:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    tmpfs:
      - /run
      - /tmp

  initdb:
    image: hammermc/renderd-docker
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=supersecret
      - OSM_PBF_URL=http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf
      - OSM2PGSQLCACHE=20000 #20gigs used only during init
      - REDOWNLOAD
      - REINITDB
      - http_proxy
      - https_proxy
    command: initdb.sh
    volumes:
      - maps-data:/data
    tmpfs:
      - /run
      - /tmp

  renderd:
    image: hammermc/renderd-docker
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersecret
    depends_on:
      - postgres
      - initdb
    command: renderd.sh
    volumes:
      - maps-data:/data
    tmpfs:
      - /run
      - /tmp

  apache:
    image: hammermc/renderd-docker
    restart: always
    depends_on:
      - renderd
    command: apache.sh
    volumes:
      - maps-data:/data
    tmpfs:
      - /run
      - /tmp
    ports:
      - 80:80

volumes:
  maps-data:
  postgres-data:
